fieldLayouts:
  a1d429fb-edf4-4896-b876-9183248da1c5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d3c78fc7-06cb-4b7d-888d-4e91f667b810
            warning: null
            width: 100
          -
            fieldUid: 55c8d23d-ad74-43a2-a3f2-8c4b6d969fe2 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 599d0f85-b7a0-4113-8df2-3f88bce23dab
            warning: null
            width: 100
          -
            fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a76b8256-0864-443d-9636-11209932cf8e
            warning: null
            width: 100
        name: Inhalt
        uid: 0a9c1935-5945-499c-b69a-f0d0d5c010cb
handle: archive
hasTitleField: false
name: Archiv
section: e1065708-fc97-4194-99c4-f62e3149cfef # Archiv
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
