field: 3ac8b547-8089-43db-b7de-39c79c658368 # Audio Files
fieldLayouts:
  8013e21a-f4e5-4d2c-bbb7-a3dd5b714a43:
    tabs:
      -
        elements:
          -
            fieldUid: 82a2d82a-ecb9-4e2d-b41d-c67f2f77f73a # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42e5b2dd-f503-40e1-9a7e-2cedc64362b5
            warning: null
            width: 100
          -
            fieldUid: 666c8cf3-0639-4757-aefa-9490930dbf0f # Audio
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9e40243-66ba-4ba6-b03e-65e5630b7ace
            warning: null
            width: 100
          -
            fieldUid: 95a20cdb-9cb3-4522-a2bf-db9721d195e8 # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dd56e4c-06a4-4b4a-93f2-5a5f08698c4f
            warning: null
            width: 100
          -
            fieldUid: dbc263da-95a4-428a-a2eb-82d51acb4523 # Artist
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 372683f5-c7db-4a8e-87c9-da587b53b4e6
            warning: null
            width: 100
          -
            fieldUid: 04d14d45-3d49-4d75-9b1b-56b1cbe51772 # Duration
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bffbd9c-f3a1-485a-95bc-427303576ddb
            warning: null
            width: 100
        name: Content
        uid: fac15c96-97d1-4434-82c7-dfa6ccaaf587
fields:
  04d14d45-3d49-4d75-9b1b-56b1cbe51772: # Duration
    columnSuffix: null
    contentColumnType: string(20)
    fieldGroup: null
    handle: duration
    instructions: 'Format 3:04'
    name: Duration
    searchable: false
    settings:
      byteLimit: null
      charLimit: 5
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  82a2d82a-ecb9-4e2d-b41d-c67f2f77f73a: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  95a20cdb-9cb3-4522-a2bf-db9721d195e8: # Titel
    columnSuffix: null
    contentColumnType: string(240)
    fieldGroup: null
    handle: heading
    instructions: null
    name: Titel
    searchable: true
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  666c8cf3-0639-4757-aefa-9490930dbf0f: # Audio
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audio
    instructions: null
    name: Audio
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - audio
      defaultUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      defaultUploadLocationSubpath: audio
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select file'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  dbc263da-95a4-428a-a2eb-82d51acb4523: # Artist
    columnSuffix: null
    contentColumnType: string(240)
    fieldGroup: null
    handle: artist
    instructions: null
    name: Artist
    searchable: true
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
